language: ruby
rvm:
 - 2.4.1

before_script:
 - chmod +x ./script/cibuild # or do this locally and commit

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: ./script/cibuild

branches:
  only:
    # Change this to gh-pages if you're deploying using the gh-pages branch
    - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build

cache: bundler # caching bundler gem packages will speed up build

# Optional: disable email notifications about the outcome of your builds
notifications:
  email: false

after_success:
  - export GIT_TAG=$TRAVIS_BRANCH-v1.0.$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "TravisCI build $TRAVIS_BUILD_NUMBER"
  - git push -q https://${GITHUB_TOKEN}@github.com/thedavecarroll/powershell.anovelidea.org --tags

deploy:
  provider: pages
  target-branch: master
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  committer-from-gh: true
  commit-message: [ci skip]
  keep-history: true
  verbose: true
  on:
    branch: master