language: ruby
rvm:
 - 2.4.1

sudo: false
cache: bundler
gemfile: Gemfile

branches:
  only:
    - master

notifications:
  email: false

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

before_script:
 - chmod +x ./script/cibuild # or do this locally and commit
 - chmod +x ./script/sitemap_ping

script: ./script/cibuild

deploy:
  provider: pages
  target-branch: gh-pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  committer-from-gh: true
  keep-history: true
  verbose: true
  on:
    branch: master

after_script: ./script/sitemap_ping
